version: "2"
services:
  nginx:
    ports:
      - "80:80"
      - "443:443"

  neurostore:
    command: /usr/local/bin/gunicorn -w 2 -b :8000 neurostore.core:app --log-level debug --timeout 120 --reload
    restart: "no"
