version: "2"
services:
  neurostore:
    restart: always
    build: ./neurostore
    expose:
      - "8000"
    volumes:
      - ./postgres/migrations:/migrations
      - ./:/neurostore
    command: /usr/local/bin/gunicorn -w 2 -b :8000 neurostore.core:app --log-level debug --timeout 120
    env_file:
      - .env

  nginx:
    restart: always
    build: ./nginx
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=neurostore.org,www.neurostore.org,test.neurostore.org
      - LETSENCRYPT_HOST=neurostore.org,www.neurostore.org,test.neurostore.org
  #  ports:
  #    - "80:80"
  #    - "443:443"
  #  volumes:
  #    - ./nginx/certs:/etc/letsencrypt
  #    - ./nginx/certs-data:/data/letsencrypt
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled:ro
    volumes_from:
      - neurostore

  postgres:
    restart: always
    build: ./postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - '5432'
    environment:
      - POSTGRES_DB=neurostuff
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env

volumes:
#  certs:
#  certs-data:
  postgres_data:

networks:
  default:
    external:
      name: nginx-proxy

