version: "2"
services:
  nginx:
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro

  swagger-ui:
    environment:
      - "API_URL=http://localhost/swagger/"

  neurostuff:
    command: /usr/local/bin/gunicorn -w 2 -b :8000 neurostuff.core:app --log-level debug --timeout 120 --reload
    restart: "no"
