version: "2"
services:
  neurostuff:
    restart: always
    build: ./neurostuff
    expose:
      - "8000"
    volumes:
      - ./postgres/migrations:/migrations
      - ./:/neurostuff
    command: /usr/local/bin/gunicorn -w 2 -b :8000 neurostuff.core:app --log-level debug --timeout 120
    env_file:
      - .env

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/certs:/etc/letsencrypt
      - ./nginx/certs-data:/data/letsencrypt
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled:ro
    volumes_from:
      - neurostuff

  postgres:
    restart: always
    build: ./postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - '5432'
    environment:
      - POSTGRES_DB=neurostuff
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env

  swagger-ui:
    image: swaggerapi/swagger-ui
    environment:
      - "API_URL=http://localhost/swagger/"
    expose:
      - '8080'

volumes:
  certs:
  certs-data:
  postgres_data:
