openapi: 3.0.0
info:
  title: neurostuff draft api
  version: '1.0'
  description: Query dataset and meta-analyses
servers:
  - url: 'http://localhost:3000'
paths:
  '/datasets/{dataset_id}':
    parameters:
      - schema:
          type: string
        name: dataset_id
        in: path
        required: true
    get:
      summary: Get User Info by User ID
      tags: []
      responses:
        '200':
          description: Dataset found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dataset'
              examples: {}
        '404':
          description: Dataset Not Found
      operationId: get-dataset-datasetid
      description: Retrieve the information of a dataset with the matching dataset ID.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
          application/xml:
            schema:
              type: object
              properties: {}
  '/studies/{study_id}':
    parameters:
      - schema:
          type: string
        name: study_id
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: Study Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/study'
        '404':
          description: Study Not Found
      operationId: get-studies-study_id
      description: Get Study ID
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
components:
  schemas:
    dataset:
      title: Dataset
      type: object
      description: ''
      x-examples:
        example-1:
          name: string
          description: string
          publication: string
          doi: string
          pmid: string
          public: true
          nimads_data: {}
          user_id: string
          user: string
      properties:
        name:
          type: string
          description: Unique identifier for the given user.
        description:
          type: string
        publication:
          type: string
        doi:
          type: string
        pmid:
          type: string
        public:
          description: Set to true if the user's email has been verified.
          type: boolean
        nimads_data:
          format: date
          description: The date that the user was created.
          type: object
        user_id:
          type: string
        user:
          type: string
      required:
        - name
        - description
        - publication
        - public
    study:
      description: ''
      type: object
      properties:
        name:
          type: string
          minLength: 1
        description:
          type: string
          minLength: 1
        publication:
          type: string
          minLength: 1
        doi:
          type: string
          minLength: 1
        pmid:
          type: string
          minLength: 1
        public:
          type: boolean
        metadata_:
          type: object
        user_id:
          type: string
          minLength: 1
        user:
          type: string
          minLength: 1
      required:
        - name
        - description
        - publication
        - doi
        - pmid
        - public
        - metadata_
        - user_id
        - user
